//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELICDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int competition_id { get; set; }
        public int airc_id { get; set; }
        public string Horse { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string clubname { get; set; }
        public string grade { get; set; }
        public int points { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Grade Grade1 { get; set; }
    }
}
