//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELICDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string username { get; set; }
        public string userpassword { get; set; }
        public int airc_id { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
