//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA2_due4NOV2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int competition_id { get; set; }
        public string competition_name { get; set; }
        public int club_id { get; set; }
        public string venue { get; set; }
        public System.DateTime competition_date { get; set; }
        public int airc_id { get; set; }
        public string competition_type { get; set; }
        public string competition_status { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Member Member { get; set; }
    }
}
