//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA2_due4NOV2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaderboard_v
    {
        public int leaderboard_id { get; set; }
        public int airc_id { get; set; }
        public string competition_type { get; set; }
        public System.DateTime competition_date { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string Horse { get; set; }
        public string clubname { get; set; }
        public int points { get; set; }
        public string grade { get; set; }
    }
}
