//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA2_due4NOV2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderEntry
    {
        public int RiderEntryID { get; set; }
        public int competition_id { get; set; }
        public int airc_id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HorsesName { get; set; }
        public string Ridergrade { get; set; }
        public Nullable<int> competition_points { get; set; }
        public string clubname { get; set; }
    }
}
